version: '3.8'

services:
  options-trading-bot:
    build: .
    container_name: momentum-options-bot
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - trading-network

  redis:
    image: redis:7-alpine
    container_name: trading-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - trading-network
    command: redis-server --save 20 1 --loglevel warning

volumes:
  redis_data:

networks:
  trading-network:
    driver: bridge