services:
  - type: web
    name: trading-bot
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      python -m pip install --upgrade pip
      pip install setuptools==69.5.1 wheel==0.43.0
      pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PIP_NO_BUILD_ISOLATION
        value: "false"
      - key: PYTHON_VERSION
        value: "3.11.9"
    autoDeploy: true
