services:
  - type: web
    name: trading-bot
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      echo "🔧 Starting aggressive Python 3.11 build..."
      python --version
      python -m pip install --upgrade pip
      python -m pip install --no-cache-dir -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PIP_NO_BUILD_ISOLATION
        value: "false"
    autoDeploy: true
